# when running test local, you can specify the image version using the env var EXAMPLE_VERSION.
# Example: EXAMPLE_VERSION=1.18.0 make

#services:
#  consul:
#    image: consul:${EXAMPLE_VERSION:-1.1.0}
#    container_name: consul
#    command: agent -server -bootstrap -client 0.0.0.0
#    environment:
#      CONSUL_LOCAL_CONFIG: '{"session_ttl_min": "1s"}'
#    healthcheck:
#      test: consul info | awk '/health_score/{if ($$3 >=1) exit 1; else exit 0}'
#    ports:
#      - 8500:8500
